'''L=[1,1.3,'2',"china",['I','am',"another",'list']]
print(L[-1:-4:-1])
print(L[4])
print(L[4][-4])
str1="hello"
str2="world"
print(str1+str2)
L=[1,1.3,'2',"china",['I','am',"another",'list']]
#L.append([666,888])
print("在没有调用方法之前的L=",L)
L.append([])
print("在调用方法append()之后的L=",L)
L.extend([])
print("在调用extend()方法之后L=",L)
L=[1,1.3,'2',"china",['I','am',"another",'list']]
L.clear()
print(L)
L=['I','love','DLL']
anotherlist=L.copy()
print("L=",L)
print("anotherlist=",anotherlist)
L.clear()
print("L=",L)
print("anotherlist=",anotherlist)
L=['I','love','DLL']
LL=L
print("L=",L)
print("LL=",LL)
L.clear()
print("L=",L)
print("LL=",LL)
L=['I','love','DLL']
Anotherlist=L
print(L)
print(Anotherlist)
L.append(9999999)
print(L)
print(Anotherlist)
L=['h','e','l','l','o','a','n','g','l','e','b','a','b','y']
print("统计'e'出现的次数为：",L.count('e'))
print("统计'l'出现的次数为：",L.count('l'))
LL=[2,0,2,0,0,1,2,0,0,0]
print("统计0出现的次数为：",LL.count(0))
LLL=[[1,2],['I','am','list'],[1,2]]
print("统计[1,2]出现的次数为：",LLL.count([1,2]))
L=['h','e','l','l','o']
L.insert(0,"dll")
print(L)
print(len(L))
L.insert(6,'dll')
print(L)
L.insert(2,'dll')
print(L)
#L.pop()
#print(L)
#L.pop(0)
#print(L)
#L.pop(1)
#print(L)
L.remove("dll")
print(L)
L.remove('l')
print(L)
L.reverse()
print(L.reverse())

str='hello world!'
str1="hello world!"
str2="I'm a good teacher"
print(str2)
str3='hello,"Tom"'
print(str3)'''

print("亲爱的%s同学，你好!您%d月的话费为%f元，余额为%f元" % ("dll",10,88.8888,66.678))